services:

  attacker:
    build: ./attacker
    container_name: attacker
    depends_on:
      email-server:
        condition: service_healthy
    restart: unless-stopped
    command: ["python", "send_email.py"]
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - soc-network

  email-server:
    image: instrumentisto/postfix:latest
    container_name: email-server
    hostname: mail
    environment:
      - maildomain=example.com
      - smtp_user=user:password
    volumes:
      - postfix_logs:/var/log/mail
      - ./postfix:/data:ro
      - ./postfix/main.cf:/etc/postfix/main.cf:ro
      - ./postfix/mailname:/etc/mailname:ro
    ports:
      - "25:25"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "postfix"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["/data/entrypoint.sh"]
    networks:
      - soc-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  wazuh-indexer:
    image: opensearchproject/opensearch:1.2.4
    container_name: wazuh-indexer
    hostname: wazuh-indexer
    environment:
      - cluster.name=wazuh-cluster
      - node.name=wazuh-indexer
      - node.master=true
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - indexer_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      soc-network:
        aliases:
          - wazuh.indexer

  wazuh-manager:
    image: wazuh/wazuh-manager:4.3.10
    container_name: wazuh-manager
    depends_on:
      wazuh-indexer:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOST=wazuh-indexer
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_PROTOCOL=http
      - ELASTICSEARCH_URL=http://wazuh-indexer:9200
    ports:
      - "1514:1514/udp"
      - "1515:1515"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "wazuh-manager"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - soc-network

  wazuh-agent:
    build: ./wazuh/agent
    image: wazuh-agent:local
    container_name: wazuh-agent
    depends_on:
      wazuh-manager:
        condition: service_healthy
    volumes:
      - postfix_logs:/var/log/mail:ro
      - ./wazuh/agent/ossec.conf:/var/ossec/etc/ossec.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "wazuh-agentd"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: >
      sh -c "/var/ossec/bin/wazuh-control start && tail -F /var/ossec/logs/ossec.log"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - soc-network

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.3.10
    container_name: wazuh-dashboard
    depends_on:
      wazuh-indexer:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://wazuh-indexer:9200
      - WAZUH_MANAGER_HOSTS=wazuh-manager
    volumes:
      - ./wazuh/dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml:ro
    ports:
      - "5601:5601"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - soc-network

networks:
  soc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postfix_logs:
    driver: local
  indexer_data:
    driver: local