services:

  attacker:
    build: ./attacker
    container_name: attacker
    depends_on:
      - email-server
    restart: unless-stopped
    command: ["python", "send_email.py"]
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - soc-network

  email-server:
    build: ./email-server
    container_name: email-server
    hostname: mail
    environment:
      - maildomain=example.com
      - smtp_user=user:password
    volumes:
      - postfix_logs:/var/log
      - ./postfix/main.cf:/etc/postfix/main.cf
      - ./postfix/aliases:/etc/aliases
      - ./wazuh/agent/ossec.conf:/var/ossec/etc/ossec.conf:ro
    ports:
      - "25:25"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pidof", "master"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    command: ["/data/entrypoint.sh"]
    networks:
      - soc-network
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 768M

  wazuh-indexer:
    image: opensearchproject/opensearch:1.2.4
    container_name: wazuh-indexer
    hostname: wazuh-indexer
    environment:
      - cluster.name=wazuh-cluster
      - node.name=wazuh-indexer
      - node.master=true
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - indexer_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 8s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 768M
    networks:
      soc-network:
        aliases:
          - wazuh.indexer

  wazuh-manager:
    image: wazuh/wazuh-manager:4.3.9
    container_name: wazuh-manager
    depends_on:
      wazuh-indexer:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOST=wazuh-indexer
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_PROTOCOL=http
      - ELASTICSEARCH_URL=http://wazuh-indexer:9200
      - ELASTICSEARCH_SSL_VERIFY=false
      - ELASTICSEARCH_SSL_CA=false
      - ELASTICSEARCH_SSL_CERT=false
      - ELASTICSEARCH_SSL_KEY=false
    volumes:
      - postfix_logs:/var/log
      - ./wazuh/manager/filebeat.yml:/etc/filebeat/filebeat.yml:ro
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep wazuh-analysisd && pgrep wazuh-db && pgrep wazuh-remoted"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 192M
    networks:
      - soc-network

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.3.10
    container_name: wazuh-dashboard
    depends_on:
      wazuh-indexer:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://wazuh-indexer:9200
    volumes:
      - ./wazuh/dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml:ro
      - ./wazuh/dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml:ro
    ports:
      - "5601:5601"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:5601/"]
      interval: 15s
      timeout: 8s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 192M
    networks:
      - soc-network

networks:
  soc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postfix_logs:
    driver: local
  indexer_data:
    driver: local