services:

  attacker:
    build: ./attacker
    container_name: attacker
    depends_on:
      - email-server
    command: ["python", "send_email.py"]

  email-server:
    image: instrumentisto/postfix:latest
    container_name: email-server
    hostname: mail
    environment:
      - maildomain=example.com
      - smtp_user=user:password
    volumes:
      - postfix_logs:/var/log/mail
      - ./postfix/main.cf:/etc/postfix/main.cf:ro
      - ./postfix/mailname:/etc/mailname:ro
      - ./postfix/aliases:/etc/aliases:ro
    ports:
      - "25:25"
    command: >
      sh -c "postalias /etc/aliases && /bin/bash -c 'postfix start && tail -F /var/log/mail/mail.log'"

  wazuh-agent:
    build: ./wazuh/agent
    image: wazuh-agent:local
    container_name: wazuh-agent
    depends_on:
      - wazuh-manager
    volumes:
      - postfix_logs:/var/log/mail:ro
      - ./wazuh/agent/ossec.conf:/var/ossec/etc/ossec.conf:ro
    command: >
      /var/ossec/bin/wazuh-control start
      && tail -F /var/ossec/logs/ossec.log

  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.3.10
    container_name: wazuh-indexer
    environment:
      - cluster.name=wazuh-cluster
      - node.name=wazuh-indexer
      - node.master=true
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - indexer_data:/usr/share/wazuh-indexer/data
    ports:
      - "9200:9200"

  wazuh-manager:
    image: wazuh/wazuh-manager:4.3.10
    container_name: wazuh-manager
    depends_on:
      - wazuh-indexer
    environment:
      - ELASTICSEARCH_HOST=wazuh-indexer
      - ELASTICSEARCH_PORT=9200
    ports:
      - "1514:1514/udp"
      - "1515:1515"

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.3.10
    container_name: wazuh-dashboard
    depends_on:
      - wazuh-manager
      - wazuh-indexer
    environment:
      - ELASTICSEARCH_HOSTS=http://wazuh-indexer:9200
      - WAZUH_MANAGER_HOSTS=wazuh-manager
    volumes:
      - ./wazuh/dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml:ro
    ports:
      - "5601:5601"

volumes:
  postfix_logs:
  indexer_data: